language: scala
dist: trusty
scala:
  - 2.13.8
  - 2.12.15
  - 3.1.1
jdk:
  - oraclejdk8
sudo: false
services:
  - rabbitmq
notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
